"""g2_core.py -- G2 engine for the F2_CONTROLE_G2 campaign (PRE_REGISTRO.md).

Design (pre-registered): the model classes are parametrized by a GENERATOR
STACK, not by N, so that the SAME code runs SU(3) (Gell-Mann stack, gate G7)
and G2 (octonionic stack).  Substrate + estimators are imported byte-identical
from N1's sun_core.py (which itself imports FL1's su3_core.py verbatim).

g2 construction: so(7) = 21 antisymmetric 7x7; the associative 3-form phi
(Fano lines (123),(145),(176),(246),(257),(347),(365)) projects so(7) -> R^7,
A |-> (sum_jk phi_ijk A_jk)_i ; g2 is the 14-dim kernel.  Hermitian generators
T_a = -i A_a with Tr(T_a T_b) = 2 delta_ab (FL1 convention).  exp(i phi.T) is
real orthogonal and lies in G2 (exponential of g2).

No QCD number enters; 14, 4 (Dynkin index) and Z are group theory.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "N1_CONTROLE_SU4"))

import sun_core as sc  # noqa: E402  (re-exports su3_core substrate verbatim)

PI = np.pi

# Fano lines of the octonion product e_i e_j = e_k (standard Cayley set).
FANO = [(1, 2, 3), (1, 4, 5), (1, 7, 6), (2, 4, 6), (2, 5, 7), (3, 4, 7),
        (3, 6, 5)]


# =========================================================================== #
# PART 0 -- the g2 generator stack
# =========================================================================== #
def _phi_tensor():
    phi = np.zeros((7, 7, 7))
    for (i, j, k) in FANO:
        i, j, k = i - 1, j - 1, k - 1
        for (a, b, c, s) in [(i, j, k, 1), (j, k, i, 1), (k, i, j, 1),
                             (j, i, k, -1), (i, k, j, -1), (k, j, i, -1)]:
            phi[a, b, c] = s
    return phi


def so7_basis():
    """21 antisymmetric E_ij - E_ji (i<j), Tr(A^T B) = 2 delta."""
    basis = []
    for i in range(7):
        for j in range(i + 1, 7):
            A = np.zeros((7, 7))
            A[i, j] = 1.0
            A[j, i] = -1.0
            basis.append(A)
    return np.array(basis)


def g2_generators():
    """(14, 7, 7) Hermitian stack T_a = -i A_a, Tr(T_a T_b) = 2 delta_ab."""
    phi = _phi_tensor()
    basis = so7_basis()
    # constraint rows: for each i, sum_jk phi[i,j,k] A[j,k] = 0
    M = np.einsum("ijk,bjk->ib", phi, basis)      # (7, 21)
    _, s, Vh = np.linalg.svd(M)
    null_mask = np.zeros(21, bool)
    null_mask[len(s):] = True                      # rows beyond rank
    tol = 1e-10 * max(s) if len(s) else 1.0
    nvecs = [Vh[r] for r in range(21) if (r >= len(s) or s[r] < tol)]
    coeffs = np.array(nvecs)                       # orthonormal in coeff space
    A = np.einsum("ab,bij->aij", coeffs, basis)    # Tr(A_a^T A_b) = 2 delta
    T = -1j * A.astype(complex)
    return T, phi


def haar_walk(T, n, rng, steps=60, scale=1.0):
    """~Haar samples on the compact group generated by stack T: product of
    `steps` exponentials with Gaussian coordinates (random walk mixes)."""
    dimA = T.shape[0]
    N = T.shape[-1]
    U = np.broadcast_to(np.eye(N, dtype=complex), (n, N, N)).copy()
    for _ in range(steps):
        phi = scale * rng.standard_normal((n, dimA))
        U = sc.sun_from_coords(T, phi) @ U
    return U


# =========================================================================== #
# PART 1 -- stack-parametrized chiral model (line-for-line SUNChiralModel)
# =========================================================================== #
class StackChiralModel:
    """Vectorised colour-Metropolis for the principal-chiral field on a causal
    graph, parametrized by a generator stack T and a hot-start sampler."""

    def __init__(self, graph, T, sampler, J, seed=0, step=0.4, init=None):
        self.g = graph
        self.T = T
        self.N = int(T.shape[-1])
        self.dimA = int(T.shape[0])
        self.dimV = 2 * self.N * self.N
        self.J = float(J)
        self.rng = np.random.default_rng(seed)
        self.step = float(step)
        if init == "ordered":
            self.U = np.broadcast_to(np.eye(self.N, dtype=complex),
                                     (graph.n, self.N, self.N)).copy()
        else:
            self.U = sampler(graph.n, self.rng)
        self.v = sc.u_to_vec(self.U)

    def _color_field(self, c):
        nbr, seg, m = self.g._nbr[c], self.g._seg[c], self.g.groups[c].size
        H = np.empty((m, self.dimV))
        for k in range(self.dimV):
            H[:, k] = np.bincount(seg, weights=self.v[nbr, k], minlength=m)
        return H

    def _propose_accept(self, c, H):
        nodes = self.g.groups[c]
        m = nodes.size
        phi = self.step * self.rng.standard_normal((m, self.dimA))
        R = sc.sun_from_coords(self.T, phi)
        Uprop = R @ self.U[nodes]
        vprop = sc.u_to_vec(Uprop)
        dE = -self.J * np.sum((vprop - self.v[nodes]) * H, axis=1)
        p = np.exp(-np.clip(dE, 0.0, 50.0))
        acc = self.rng.random(m) < p
        self.U[nodes[acc]] = Uprop[acc]
        self.v[nodes[acc]] = vprop[acc]
        return int(acc.sum())

    def sweep(self):
        acc = 0
        for c in range(self.g.n_colors):
            if self.g.groups[c].size == 0:
                continue
            acc += self._propose_accept(c, self._color_field(c))
        return acc / max(self.g.n, 1)

    def equilibrate(self, n_burn, adapt=True, target=0.4):
        for s in range(n_burn):
            a = self.sweep()
            if adapt and (s + 1) % 25 == 0:
                if a > target + 0.1:
                    self.step *= 1.15
                elif a < target - 0.1:
                    self.step *= 0.87
                self.step = float(np.clip(self.step, 1e-3, 3.0))

    def order_parameter(self):
        return float(np.linalg.norm(self.v.mean(axis=0)))

    def corr_arrays(self):
        return [self.v[:, k] for k in range(self.dimV)]


# =========================================================================== #
# PART 2 -- Goldstone twists for a generator stack (verbatim protocol)
# =========================================================================== #
def goldstone_twists_stack(T, sampler, L=14):
    rng = np.random.default_rng(0)
    N = T.shape[-1]
    U0 = sampler(1, rng)[0]
    base = np.broadcast_to(U0, (L, L, L, N, N)).copy()
    E0 = sc.chiral_energy_grad(base, 1.0)
    x = np.arange(L)
    ks = [2 * PI * nk / L for nk in (1, 2, 3)]
    modes = {}
    n_gapless = 0
    for a in range(T.shape[0]):
        dEs, stiff = [], []
        for k in ks:
            Xtw = sc.sun_exp((k * x)[:, None, None] * T[a][None])
            U = np.einsum("aij,jk->aik", Xtw, U0)
            field = np.broadcast_to(U[:, None, None], (L, L, L, N, N)).copy()
            Et = sc.chiral_energy_grad(field, 1.0)
            dEs.append(float(Et - E0))
            stiff.append(float((Et - E0) / k ** 2))
        gapless = (dEs[0] > 0) and (dEs[0] < dEs[-1]) and (stiff[0] > 1e-6)
        n_gapless += int(gapless)
        modes[f"gen_{a}"] = {"gapless": bool(gapless), "dE": dEs}
    return {"expected": int(T.shape[0]), "found": n_gapless, "modes": modes}


# =========================================================================== #
# PART 3 -- topology: SO(4) subgroup, diagonal so(3), G2 hedgehog (B -> 4)
# =========================================================================== #
def _lin_solve_subspace(T, row_constraints):
    """Vectors in span(T) whose matrices satisfy the given linear constraints.
    row_constraints: callable M -> flat residual array."""
    dimA = T.shape[0]
    rows = []
    probe = [row_constraints(T[a]) for a in range(dimA)]
    M = np.array([np.asarray(p).ravel() for p in probe]).T.real  # (ncon, dimA)
    Mi = np.array([np.asarray(p).ravel() for p in probe]).T.imag
    M = np.vstack([M, Mi])
    _, s, Vh = np.linalg.svd(M)
    ns = [Vh[r] for r in range(dimA) if (r >= len(s) or s[r] < 1e-10 * max(s))]
    return np.array(ns)                                        # coeff vectors


def so4_split(T):
    """S = {A in g2 : A preserves span(e1,e2,e3)} = so(4); split into the two
    su(2) ideals; return (Xs, Ys): X acts on the 3-block as so(3) (+ spin-1/2
    on the 4-block), Y acts only on the 4-block."""
    # constraint: lower-left 4x3 block of the (antisymmetric) matrix vanishes
    coeffs = _lin_solve_subspace(T, lambda M: M[3:, :3])
    S = np.einsum("ab,bij->aij", coeffs, T)                    # (dimS, 7, 7)
    dimS = S.shape[0]
    # kernel of the 3-block action = ideal Y (acts only on 4-part)
    M3 = np.array([S[a][:3, :3].ravel() for a in range(dimS)]).T
    M3 = np.vstack([M3.real, M3.imag])
    _, s3, Vh3 = np.linalg.svd(M3)
    ker = [Vh3[r] for r in range(dimS)
           if (r >= len(s3) or s3[r] < 1e-10 * max(s3))]
    Yc = np.array(ker)
    Y = np.einsum("ab,bij->aij", Yc, S)
    # X ideal = Tr-orthogonal complement of Y inside S
    G = np.einsum("aij,bji->ab", S, Y).real / 2.0              # overlaps
    # projector onto complement in coefficient space
    Q, _ = np.linalg.qr(Yc.T)
    P = np.eye(dimS) - Q @ Q.T
    Xc_raw = P
    # orthonormalize surviving directions
    u, sv, _ = np.linalg.svd(Xc_raw)
    Xc = u[:, sv > 1e-8].T
    X = np.einsum("ab,bij->aij", Xc, S)
    return X, Y


def _su2_triple(W, block=False):
    """From a 3-dim su(2) stack W (Hermitian), build (J1,J2,J3) with
    [J1,J2] = i J3 cyclic.
    block=True: align exactly with the standard spin-1 matrices
    (L_a)_{bc} = -i eps_{abc} in the upper 3x3 block (the block action is an
    algebra iso, so exact block alignment gives exact global closure).
    block=False: orthonormal basis + rescale by the structure constant."""
    assert W.shape[0] == 3
    eps = np.zeros((3, 3, 3))
    eps[0, 1, 2] = eps[1, 2, 0] = eps[2, 0, 1] = 1
    eps[0, 2, 1] = eps[1, 0, 2] = eps[2, 1, 0] = -1
    if block:
        Ls = [-1j * eps[a] for a in range(3)]                  # Hermitian L_a
        Wb = np.array([W[a][:3, :3] for a in range(3)])
        A = np.array([Wb[a].ravel() for a in range(3)]).T      # (9, 3)
        A = np.vstack([A.real, A.imag])
        Js = []
        for k in range(3):
            b = np.concatenate([Ls[k].ravel().real, Ls[k].ravel().imag])
            c, *_ = np.linalg.lstsq(A, b, rcond=None)
            Js.append(np.einsum("a,aij->ij", c, W))
        return np.array(Js)
    # orthogonalize to equal Tr-norm (invariant form => f_abc = c eps_abc)
    G = np.einsum("aij,bji->ab", W, W).real
    Linv = np.linalg.inv(np.linalg.cholesky(G))
    Wo = np.einsum("ab,bij->aij", Linv, W)                     # Tr(WaWb)=delta
    C12 = (Wo[0] @ Wo[1] - Wo[1] @ Wo[0]) / 1j
    c = float(np.trace(C12 @ Wo[2]).real / np.trace(Wo[2] @ Wo[2]).real)
    # [W1/c, W2/c] = (1/c^2)(i c W3) = i (W3/c)  => J_k = W_k / c
    return Wo / c


def diag_so3(T):
    """The diagonal so(3) of SO(4) in G2 (7 = 3+3+1): Hermitian triple
    (J1,J2,J3), [J1,J2] = i J3 cyclic; n.J has spectrum {+-1,+-1,0,0,0}."""
    X, Y = so4_split(T)
    JX = _su2_triple(X, block=True)
    # scale JX so that its 3-block equals the exact L_a (spin-1 unit): then
    # [JX1, JX2] = i JX3 automatically in the block; verify globally below.
    JY = _su2_triple(Y)
    # align signs: require [JY1,JY2] = +i JY3
    C = (JY[0] @ JY[1] - JY[1] @ JY[0]) / 1j
    if np.trace(C @ JY[2]).real < 0:
        JY[2] = -JY[2]
    # match normalization: JY spins are 1/2 on the 4-block; the triple from
    # _su2_triple already has unit structure constants.
    J = JX + JY
    return J, JX, JY


def su2_residual(J):
    """max_k || [J_k, J_{k+1}] - i J_{k+2} ||_max (cyclic)."""
    r = 0.0
    for k in range(3):
        C = J[k] @ J[(k + 1) % 3] - J[(k + 1) % 3] @ J[k] - 1j * J[(k + 2) % 3]
        r = max(r, float(np.max(np.abs(C))))
    return r


def g2_hedgehog(J, L, half_width=2.6, charge=+1, w_core=0.8):
    """G2 Skyrmion via the diagonal so(3): U = exp(i F(r) n.J), F = 2pi
    exp(-r/w) (F(0)=2pi is single-valued because all J-spins are integer).
    Predicted B_inf = Dynkin index = 4 (PRE_REGISTRO)."""
    x = np.linspace(-half_width, half_width, L)
    dx = float(x[1] - x[0])
    X, Yg, Z = np.meshgrid(x, x, x, indexing="ij")
    r = np.sqrt(X ** 2 + Yg ** 2 + Z ** 2)
    rs = np.where(r > 0, r, 1.0)
    nx, ny, nz = X / rs, Yg / rs, Z / rs
    nx[r == 0] = ny[r == 0] = nz[r == 0] = 0.0
    if charge < 0:
        nz = -nz
    F = 2.0 * PI * np.exp(-r / w_core)
    H = (nx[..., None, None] * J[0] + ny[..., None, None] * J[1]
         + nz[..., None, None] * J[2])
    U = sc.sun_exp(F[..., None, None] * H)
    return U, dx


# =========================================================================== #
# PART 4 -- gauge sector for a generator stack (verbatim formulas)
# =========================================================================== #
def gauge_init_stack(sampler, N, L, rng, hot=True):
    shape = (4, L, L, L, L)
    if hot:
        return sampler(int(np.prod(shape)), rng).reshape(shape + (N, N))
    return np.broadcast_to(np.eye(N, dtype=complex), shape + (N, N)).copy()


def gauge_metropolis_sweep_stack(U, beta, rng, step, T, n_hit=2):
    N = U.shape[-1]
    dimA = T.shape[0]
    L = U.shape[1]
    g = np.arange(L)
    I, Jm, K, Tt = np.meshgrid(g, g, g, g, indexing="ij")
    parity = (I + Jm + K + Tt) % 2
    acc_tot = cnt_tot = 0
    for mu in range(4):
        A = sc.staple_sum(U, mu)
        for par in (0, 1):
            mask = parity == par
            for _ in range(n_hit):
                Uold = U[mu][mask]
                Amask = A[mask]
                R = sc.sun_from_coords(
                    T, step * rng.standard_normal((Uold.shape[0], dimA)))
                Uprop = R @ Uold
                dtr = np.real(np.trace((Uprop - Uold) @ sc.dagger(Amask),
                                       axis1=-2, axis2=-1))
                dS = -(beta / N) * dtr
                p = np.exp(-np.clip(dS, 0.0, 50.0))
                a = rng.random(Uold.shape[0]) < p
                blk = U[mu][mask]
                blk[a] = Uprop[a]
                U[mu][mask] = blk
                acc_tot += int(a.sum())
                cnt_tot += a.size
    return acc_tot / max(cnt_tot, 1)


if __name__ == "__main__":
    T, phi = g2_generators()
    print(f"g2 stack: {T.shape[0]} generators (expect 14)")
    G = np.einsum("aij,bji->ab", T, T).real
    print(f"Tr-norm err: {np.max(np.abs(G - 2*np.eye(T.shape[0]))):.2e}")
